### ISSUE TITLE
errors when loading

### ISSUE THREAD

**Issue by stats-matt** [stats-matt/doenet-analyzer#23]
errors are caused in clean events by `filter((timestamp > min_date) & (timestamp < max_date))`
and
`version_filter` until the data gets loaded

**Comment by Jacobrl** [comment]
I think I found something interesting [https://shiny.posit.co/r/articles/improve/sanitize-errors/](here is the link). In code, it would be options(shiny.sanitize.errors = FALSE)

**Comment by stats-matt** [comment]
Excellent - that sounds like a good solution

**Comment by stats-matt** [comment]
Just gave this a try - it seems like it doesn't actually change it
